version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    # Limit the number of open pull requests for npm dependencies
    open-pull-requests-limit: 5
    # Reviewers to request for dependency updates
    reviewers:
      - "zachlagden"
    # Assignees for dependency updates
    assignees:
      - "zachlagden"
    # Labels to add to dependency update PRs
    labels:
      - "dependencies"
      - "npm"
    # Commit message prefix
    commit-message:
      prefix: "⬆️"
      include: "scope"
    # Group related updates
    groups:
      next-ecosystem:
        patterns:
          - "next*"
          - "@next/*"
          - "react*"
          - "@types/react*"
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "typescript"
          - "autoprefixer"
          - "postcss"
          - "tailwindcss*"
        update-types:
          - "minor"
          - "patch"
      security-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"
    # Ignore specific dependencies that need manual updates
    ignore:
      - dependency-name: "node"
        # Ignore major version updates for Node.js
        update-types: ["version-update:semver-major"]
    # Auto-merge configuration for minor and patch updates
    rebase-strategy: "auto"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "⬆️"
      include: "scope"
